services:
  robotnik_simulator:
    container_name: robotnik_simulator
    image: robotnik_simulation-robotnik_simulation:latest
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        base_image: robotnik/ros
        ros_distro: jazzy
        image_base_version: 0.6.2
        ros_mirror: ros.mirror.robotnik.ws
    network_mode: host
    privileged: true
    
    # 1. Aseguramos el runtime
    runtime: nvidia
    
    environment:
      - ROS_DOMAIN_ID=0
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      # 2. Configuración GPU Completa
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      # 3. Variables OBLIGATORIAS para tu Laptop (Render Offload)
      - __NV_PRIME_RENDER_OFFLOAD=1
      - __GLX_VENDOR_LIBRARY_NAME=nvidia
    
    volumes:
      # 4. CORREGIDO: Esto debe ser un volumen, NO un device
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      
    devices:
      - /dev/dri:/dev/dri

  robotnik_robot_spawner:
    container_name: robotnik_robot_spawner
    image: robotnik_simulation-robotnik_simulation:latest
    network_mode: host
    privileged: true
    
    # Runtime también aquí
    runtime: nvidia
    
    env_file:
      - env/robot.env
    environment:
      - ROS_DOMAIN_ID=0
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - ROS_BU_LAUNCH=spawn_robot.launch.py robot:=$${ROBOT} robot_model:=$${ROBOT_MODEL} has_arm:=$${HAS_ARM}
      # También aquí por seguridad si este nodo necesita contexto gráfico
      - __NV_PRIME_RENDER_OFFLOAD=1
      - __GLX_VENDOR_LIBRARY_NAME=nvidia
      
    volumes:
      # CORREGIDO: Movido de devices a volumes
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./entrypoint.sh:/usr/local/bin/ros_entrypoint.sh
      
    devices:
      - /dev/dri:/dev/dri
      
    depends_on:
      robotnik_simulator:
        condition: service_healthy